name: CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - '!.github/workflows/ci.yaml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Unit tests
        run: pnpm test
      - name: E2E tests
        run: pnpm test:e2e
